import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Button from '../components/Button'
import Menu from '../components/Menu'
import { LinkIcon, TrashIcon } from '@heroicons/react/24/solid'
import { useRouter } from 'next/router'

const Home: NextPage = () => {

  const router = useRouter()

  return (
    <div className='container mx-auto'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Menu/>

      {/* header */}
      <div className='flex flex-col place-items-center py-44 space-y-3'>
        <h1 className='text-5xl font-bold'>Ayo mulai Voting</h1>
        <h2 className='text-lg bg-zinc-100 py-3 py-1'>Web Voting No. Sekian Di indonesia</h2>
        <Image alt={"Header"} src={"/assets/org.png"} width={274} height={243}/>
        <div className='space-x-10'>
          <Button text='Buat Vote Baru' className='font-bold' onClick={()=>router.push("/vote/create")}/>
          <Button text='Ikutan Vote' type='secondary' className='font-bold' onClick={()=>router.push("/participant")}/>
        </div>
      </div>
      {/* /header */}

      {/* table */}
        <div>
          <p className='py-5 text-lg font-bold'>vote yang saya buat</p>
          <table className='table-auto w-full border border-zinc-100'>
            <thead>
              <tr className='border-b border-zinc-100'>
                <th className='p-5 text-left'>No</th>
                <th className='p-5 text-left'>Judul</th>
                <th className='p-5 text-left'>Kandidat</th>
                <th className='p-5 text-left'>kode</th>
                <th className='p-5 text-left'>Mulai</th>
                <th className='p-5 text-left'>Selesai</th>
                <th className='p-5 text-left'></th>
              </tr>
            </thead>

            <tbody>
              <tr>
                <td className='p-5 text-left'>1</td>
                <td className='p-5 text-left'>Judul</td>
                <td className='p-5 text-left'>Budi vs anton</td>
                <td className='p-5 text-left'>BXSIDW</td>
                <td className='p-5 text-left'>20 oct 2022 11:00</td>
                <td className='p-5 text-left'>22 oct 2022 11:00</td>
                <td className='p-5 text-left'>
                  <div>
                    <a href='#'>
                      <LinkIcon className='w-8 h-8 p-2 hover:bg-zinc-100'/>
                    </a>
                    <a href='#'>
                      <TrashIcon className='w-8 h-8 p-2 hover:bg-zinc-100'/>
                    </a>
                  </div>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      {/* /table */}
    </div>
  )
}

export default Home
